services:
  public_site:
    build:
      context: ./apps/public_site
      dockerfile: Dockerfile
    container_name: public_site
    ports:
      - '3000:3000'
    volumes:
      - ./apps/public_site:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.public_site.rule=Host(`mittforetag.localhost`)"
      - "traefik.http.routers.public_site.entrypoints=web-secure"
      - "traefik.http.routers.public_site.tls=true"
      - "traefik.http.routers.public_site.tls.domains[0].main=mittforetag.localhost"

  my_pages:
    build:
      context: ./apps/my_pages
      dockerfile: Dockerfile
    container_name: my_pages
    ports:
      - '3001:3000'
    volumes:
      - ./apps/my_pages:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.my_pages.rule=Host(`mypages.mittforetag.localhost`)"
      - "traefik.http.routers.my_pages.entrypoints=web-secure"
      - "traefik.http.routers.my_pages.tls=true"
      - "traefik.http.routers.my_pages.tls.domains[0].sans=*.mittforetag.localhost"

  traefik:
    image: traefik:v3.1.2
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web-secure.address=:443"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik"
      - "--providers.file.watch=true"
    ports:
      # The HTTP port
      - "80:80"
      # The HTTPS port
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      # Config
      - ./.traefik/config:/etc/traefik:ro
      # Certificate store
      - ./.traefik/certs:/etc/certs:ro
