services:
  public_site:
    build:
      context: ./apps/public_site
      dockerfile: Dockerfile
    container_name: public_site
    ports:
      - '3000:3000'
    volumes:
      - ./apps/public_site:/app

  my_pages:
    build:
      context: ./apps/my_pages
      dockerfile: Dockerfile
    container_name: my_pages
    ports:
      - '3001:3000'
    volumes:
      - ./apps/my_pages:/app
