services:
  public_site:
    build:
      context: ./apps/public_site
      dockerfile: Dockerfile
    container_name: public_site
    ports:
      - '3000:3000'
    volumes:
      - ./apps/public_site:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.public_site.rule=Host(`mittforetag.localhost`)"

  my_pages:
    build:
      context: ./apps/my_pages
      dockerfile: Dockerfile
    container_name: my_pages
    ports:
      - '3001:3000'
    volumes:
      - ./apps/my_pages:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.my_pages.rule=Host(`mypages.mittforetag.localhost`)"

  traefik:
    image: traefik:v3.1.2
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--providers.docker.exposedbydefault=false"
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock